### ISSUE TITLE
Great post, but gifs make it unreadable

### ISSUE THREAD

**Issue by alberto-santini** [polynome/polynome.github.io#1]
Guys, congratulations on winning the competition and props for a post extremely engaging and fun to read. However, all the gifs make it very hard to focus on the text. Besides, they serve no apparent purpose.

[This](http://polynome.co/infosec/inversoft/elasticsearch/linode/penetration-testing/2016/08/16/hack-that-inversoft.html) is the incriminated post. [This](https://news.ycombinator.com/item?id=12361318) is an HN thread that shows that I am not the only one to find this problematic.

Thanks!

**Comment by bjabes** [comment]
Fixed!
